[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -I src

; If you prefer to build against esp-idf compatibility layer, uncomment below
; build_flags = -DESP_IDF_COMPAT
